/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "spi.h"

void delay(void){
	for(uint32_t i=0; i<500000; i++);
}

gpio_dev_t led_dev = GPIO_INSTANCE(D, 12);
gpio_port_config_t led_config = DK_LED_GPIO_CONFIG();

gpio_dev_t button_dev = GPIO_INSTANCE(A, 0);
gpio_port_config_t button_config = DK_BUTTON_GPIO_CONFIG();

int main(void){
	GPIO_PeriClockControl(led_dev.gpio_peri, 1);
	GPIO_Init(&led_dev, &led_config);

	GPIO_PeriClockControl(button_dev.gpio_peri, 1);
	GPIO_Init(&button_dev, &button_config);

	IRQConfig(GPIO_port_IRQNumber(0), 1);
	IRQ_Priority_Config(GPIO_port_IRQNumber(0), 15);

	while(1){
//		if(GPIO_Get_Port_Input(&button_dev) == 1)
//			GPIO_toggle_Port_Output(&led_dev);
//		delay();
	}
}

//overwrite the IRQHandler of EXIT0 in startup file
void EXTI0_IRQHandler(void){
	GPIO_IRQHandler(0);
	GPIO_toggle_Port_Output(&led_dev);
}
