/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"

void delay(void){
	for(uint32_t i=0; i<500000; i++);
}

int main(void){
	gpio_dev_t led_dev;
	gpio_port_config_t led_config;
	led_dev.gpio_peri = GPIOD;
	led_dev.pin = 12;
	led_config.mode = GPIO_MODE_GP_OUTPUT;
	led_config.output_type = GPIO_OUTPUT_PUSH_PULL;
	led_config.pull_up_down = GPIO_NO_PUPD;

	gpio_dev_t button_dev;
	gpio_port_config_t button_config;
	button_dev.gpio_peri = GPIOA;
	button_dev.pin = 0;
	button_config.mode = GPIO_MODE_IR_FE;
	button_config.pull_up_down = GPIO_NO_PUPD;

	GPIO_PeriClockControl(led_dev.gpio_peri, 1);
	GPIO_Init(&led_dev, &led_config);

	GPIO_PeriClockControl(button_dev.gpio_peri, 1);
	GPIO_Init(&button_dev, &button_config);
//
//	IRQConfig(IRQ_NUM_EXTI0, 1);
//	IRQ_Priority_Config(IRQ_NUM_EXTI0, 15);

	while(1){
		if(GPIO_Get_Port_Input(&button_dev) == 1)
			GPIO_toggle_Port_Output(&led_dev);
		delay();
	}
}

//overwrite the IRQHandler of EXIT0 in startup file
//void EXTI0_IRQHandler(void){
//	GPIO_IRQHandler(0);
//	GPIO_toggle_Port_Output(GPIOD, 12);
//}
